### ISSUE TITLE
!unaban and !unshban command for moderators to remove S&H & Academics bans

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#10]
Similar to the unmute command, !unaban and !unshban (aliases !aunban & !shunban) should remove the punishment end time from the `punishments` table, remove the relevant role from the user so they can access those channels again, and send them a direct message to inform them.

Format of commands is as follows:
`!unshban @user`

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by Vortex2wenty** [comment]
Hey, can I work on this? Thanks.

**Comment by injejiblegames** [comment]
I will do this!

**Comment by jotslo** [comment]
Does not apply anymore
