### ISSUE TITLE
!latex command for anyone to convert text to latex in #maths channel

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#11]
We are in need of a latex command to be used **primarily** in our #maths channel (351182527316099072), which should take text input and send an image showing the LaTeX equivalent to make it easier for members to visualise equations.

The bot should not permanently save images on the server that hosts the bot in order to save storage.

Ideal Format:
`!latex 3+7`

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility. Additionally, **this command was not completed in the previous bot**.

**Comment by andrewpriority** [comment]
Finished this!

**Comment by viperize** [comment]
assuming this has not been closed yet?

**Comment by andrewpriority** [comment]
I solved this issue a while ago but I haven't received a reply yet... Just waiting on Josh

**Comment by jotslo** [comment]
Does not apply anymore
