### ISSUE TITLE
!info command for moderators

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#12]
We are in need of an `!info` command for moderators to use, which gives them moderation information about a user.

Required Information:
- Username
- Join Date
- Mute Count
- Kick Count
- Ban Count
- S&H Ban Count
- Academics Ban Count

Ideally, it should also be able to use the [RoVer API](https://verify.eryn.io/api) so the info command also shows the Roblox username of members if applicable.

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by sammckee** [comment]
currently working on this. How do I query the join date?

**Comment by jotslo** [comment]
@sammckee You will need to use `member.joined_at`, as shown in the discord.py docs [here](https://discordpy.readthedocs.io/en/latest/api.html#discord.Member.joined_at).

**Comment by sammckee** [comment]
@jotslo done! thanks for the push in the right direction

**Comment by sammckee** [comment]
@jotslo any more feedback?
