### ISSUE TITLE
!derole command for administrators to remove GJ participant roles

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#13]
When an administrator types `!derole`, the bot should iterate through each member with the GJ Participant role (350934544628580362) and remove their role. Exceptions should also be caught to ensure that the bot doesn't stop iterating through the users if one causes an error, as there are usually over 100 members with the role at a given time.

The bot should send a message when starting and another when the process has been finished to make it easier to see whether the command is or isn't working, as it would be expected to take a while to complete due to the amount of members it has to iterate through.

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by bryiac** [comment]
Heyo! lemme do this one
