### ISSUE TITLE
Automatically update user's level when reached point threshold

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#14]
After a user's point count has been changed, the bot should automatically update the user's level in the database if applicable. If the level is updated, an embed should also be sent to congratulate the user on being levelled up to level `x`.

Level is calculated by the following algorithm: `1 + (math.floor(0.3 * math.sqrt(user_points)))`

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by fly-san** [comment]
I'll take that 😄

**Comment by jotslo** [comment]
Apologies for the extremely late response, we are going to be making modifications that make contributing much easier, and adding new contributors to the repository shortly to ensure that the bot continues to stay maintained.

This has now been implemented.
