### ISSUE TITLE
Automatically award users with roles when applicable

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#15]
Users should be automatically be given roles when they reach the thresholds outlined below. An embed should also be sent to congratulate them on reaching the role.

The bot should award the role if the user's points are *greater* than the amount outlined and they do not already have the role. This prevents the bot from skipping the achievement if they earn more than one point at a time.

- 30 points + 3 days in server -> Verified Lvl. 2 (352799502379253772)
- 2,000 points -> Regular (322102125402259456)
- 10,000 points -> 10,000+ Club (642852174854094868)
- 20,000 points -> 20,000+ Club (642852176628285455)
- 50,000 points -> 50,000+ Club (642852191606013963)
- 100,000 points -> 100,000+ Club (550880780776374296) + Custom // Gold (639147821273972736)

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by fly-san** [comment]
I'll take this one too

**Comment by jotslo** [comment]
Apologies for the extremely late response, we are going to be making modifications that make contributing much easier, and adding new contributors to the repository shortly to ensure that the bot continues to stay maintained.

This has now been implemented.
