### ISSUE TITLE
Anti-spam feature that can punish users for spammy messages

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#16]
The bot needs to have the following anti-spam features:
- Deleting messages with 100+ characters in which 30% of the message contains the same character.
- Muting the user for 30 minutes if 5 messages sent within the last 1 minute are identical **(ignore messages with a blank message content)**
- Muting the user for 30 minutes if 5 messages are sent within 1 second.

Ideas for other anti-spam features are also welcome.

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by spaceraiders0** [comment]
yeah i'll take this one.

**Comment by MeapHamster** [comment]
Does this still need completion?

**Comment by jotslo** [comment]
Does not apply anymore
