### ISSUE TITLE
Automatically award relevant donator roles

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#17]
When a user donates via our Roblox donation centre or boosts with Nitro, they need to be automatically awarded.

Robux donations appear in our #joins-and-donations channel (473852097415086090) in the following format:
```
{"user":"Josh#5318","amount":101}
**Josh#5318** has now donated a total of 101R$!
```

The bot needs to interpret the JSON on line 1 of the message and award the user with the relevant donator role, including all roles for any lower thresholds they do not already have. **Note that the amount given is the total over multiple donations, so donations do not need to be stored by the bot.**

Donation thresholds are as follows:
100R$: Donator role (323047035840233474)
1,000R$: Donator+ role (325937099557830656)
3,500R$: Custom // Gold (639147821273972736)

The user needs to also be sent a DM when they have donated to thank them and inform them which roles they have been awarded.

___________

When a user is given the `Nitro Booster` role (585533734548406305), they need to be sent a thank you message via DM, in addition to being given the `Custom // Gold` role similarly to the 3,500R$ threshold.

When a user loses the `Nitro Booster` role, their custom colour should be removed **if they do not have the Donator+ role**. The bot can do this by iterating through the user's role and removing any roles that start with `Custom //`

_________

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by skoleosho97** [comment]
Working on this. `get_member_named` is being extremely difficult, though. Any suggestions for a workaround?

EDIT: Figured out a workaround. :)

**Comment by JBetts97** [comment]
Hello @jotslo and @waifuxszn ,
Is this issue still open, can I work on this?
