### ISSUE TITLE
Rework look of !stats embed

### ISSUE THREAD

**Issue by VanishBlox** [ScriptersCF/dr-script#29]
1. Allow you to look up the stats of another SCF member, show stats for calling user if no target argument is given ("!stats @user")
2. embed thumbnail = target user's avatar
3. show the target user's rank
4. Show join date of target user
I have pasted some JSON below, paste it in the https://discohook.org/ editor and see the better version of the stats' embed

`{
  "content": null,
  "embeds": [
    {
      "title": "Stats",
      "color": 38143,
      "fields": [
        {
          "name": "User:",
          "value": "<@313676569325469696>"
        },
        {
          "name": "Rank:",
          "value": "#1"
        },
        {
          "name": "Level:",
          "value": "57",
          "inline": true
        },
        {
          "name": "Points:",
          "value": "64270"
        },
        {
          "name": "Join date:",
          "value": "1/1/2020, 14:00 **UTC**"
        }
      ],
      "thumbnail": {
        "url": "https://cdn.discordapp.com/avatars/313676569325469696/04d289302b59ced152f717b2aef6d472.webp?size=128"
      }
    }
  ]
}`

**Comment by megahypex** [comment]
Can I be assigned?

**Comment by astrobits1** [comment]
Can I be assigned?

**Comment by jotslo** [comment]
Apologies for the extremely late response, we are going to be making modifications that make contributing much easier, and adding new contributors to the repository shortly to ensure that the bot continues to stay maintained.

This has now been implemented into the bot.
