### ISSUE TITLE
Log deleted + edited messages

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#8]
The bot needs to log deleted and edited messages in a log server. The channel that messages need to be sent to has an ID of `370937658920271874` and is in a separate server that our bot already has access to.

Logged messages need to contain the following information:
- Time & Date
- Sender's Username & ID
- Message Content
- Message Channel

Logged messages also need to have tags replaced to ensure that staff members aren't tagged multiple times. Alternatively, embeds can be used which will result in tags being ignored by the Discord client.

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by ptrstr** [comment]
Could you assign me to this?

**Comment by jotslo** [comment]
@ptrstr I've assigned you to the issue, thanks in advance!

**Comment by ptrstr** [comment]
@jotslo Should you close this?
