### ISSUE TITLE
!addpoints command for moderators to give user points

### ISSUE THREAD

**Issue by jotslo** [ScriptersCF/dr-script#9]
We need a command that allows moderators and higher to award other users with points, which is stored in the `scores` table of our database, which you can find a sample of in the repository.

The command format should be as follows:
`!addpoints \@user 123`

Which will result in the user's point count being **increased by** 123. Ex: `122 -> 245`

You can refer to [our previous bot's source code](https://github.com/ScriptersCF/Discord_Bot/blob/master/bot.py) for reference. Please note that it may be difficult to navigate through due to its poor scalibility.

**Comment by bryiac** [comment]
lemme do this ?

**Comment by jotslo** [comment]
Apologies for the extremely late response, we are going to be making modifications that make contributing much easier, and adding new contributors to the repository shortly to ensure that the bot continues to stay maintained.

This has now been implemented.
